# Introduccion a Pandas

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'3.0.6'

In [3]:
# instalacion de libreria
!pip install pandas

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.10/site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

http://pandas.pydata.org/

Pandas es la extensión logica de numpy al mundo del Análisis de datos. 

De forma muy general, Pandas extrae la figura del Dataframe conocida por aquellos que usan R a python.

Un pandas dataframe es una tabla, lo que es una hoja de excel, con filas y columnas.

En pandas cada columna es una Serie que esta definida con un numpy array por debajo.

### Qué puede hacer pandas por ti?

- Cargar datos de diferentes recursos
- Búsqueda de una fila o columna en particular
- Realización de calculos estadísticos
- Processamiento de datos
- Combinar datos de múltiples recursos

# 1. Creación y Carga de Datos
---------------------------------

`Pandas` puede leer archivos de muchos tipos, csv, json, excel entre otros

Para esta seccion aprenderemos a crear un Dataframe de 0 y a leer archivos de diferentes fuentes de información.

<img src='https://pandas.pydata.org/docs/_images/02_io_readwrite.svg'>

### 1.1 Creación de dataframes

A partir de datos almacenados en diccionarios o listas es posible crear dataframes

`pd.Dataframe()`

In [10]:
import pandas as pd # pd -> alias por convención
dicx = {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth"
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }

# df -> es un Dataframe
df = pd.DataFrame(dicx)

In [8]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [3]:
# creacion de df a partir de una lista
lista = [
            ["Rick", "Sanchez", 60],
            ["Morty", "Smith", 14]
        ]

# nombre de columnas
columnas= ["nombre", "apellido", "edad"]
df_rick_morty = pd.DataFrame(lista, columns = columnas)
df_rick_morty

  nombre apellido  edad
0   Rick  Sanchez    60
1  Morty    Smith    14

In [4]:
# tipo de dato de dataframe 
type(df_rick_morty)

pandas.core.frame.DataFrame

### 1.2 Carga de datos a partir de fuentes de información

Pandas soporta múltiples fuentes de información entre los que estan csv , sql, json,excel, etc

Para leer un archivo siempre iniciamos con : `pd.read_`

In [13]:
## Leyendo data de un "csv"
import pandas as pd
# mostrar todas las filas del df
# https://www.geeksforgeeks.org/how-to-display-all-rows-from-dataframe-using-pandas/#:~:text=A%20function%20set_option()%20is,value%20of%20max_rows%20is%2010.
# pd.set_option('display.max_rows', None) 

# csv(<ruta archivo>, sep=<separador datos>)
df = pd.read_csv('./src/input/primary_results.csv',sep=',')

In [14]:
df

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
...,...,...,...,...,...,...,...,...
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000

In [16]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [17]:
## Leyendo data de un archivo "excel"

path_ = "./src/input/fallecidos_covid.xlsx"
df_excel = pd.read_excel(path_, sheet_name='fallecidos_covid')

In [19]:
# head() -> me muestra los 5 primeros registros de mi df
#df_excel.head(2)
df_excel.head(100)

,FECHA_CORTE,UUID,FECHA_FALLECIMIENTO,EDAD_DECLARADA,SEXO,CLASIFICACION_DEF,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20210811,8ff6ea53-1467-456b-92ef-4e001ff8a2d6,20210725,65,MASCULINO,Criterio virolÃ³gico,AREQUIPA,ISLAY,PUNTA DE BOMBON,40706.0
1,20210811,71be5780-1e0d-4092-9036-af6d408d66e5,20210618,37,MASCULINO,Criterio SINADEF,PUNO,SAN ROMAN,JULIACA,211101.0
2,20210811,db55ecea-b436-4cb7-8d57-0665a90d43b2,20210713,52,MASCULINO,Criterio virolÃ³gico,LIMA,LIMA,SANTA ANITA,150137.0
3,20210811,0ab634e6-2919-40d8-8b53-90cb6a6a967a,20210416,78,FEMENINO,Criterio SINADEF,PIURA,PIURA,VEINTISEIS DE OCTUBRE,200115.0
4,20210811,991f8f70-a4d7-437e-b9eb-990c3518c591,20210328,60,MASCULINO,Criterio serolÃ³gico,PIURA,PIURA,PIURA,200101.0
...,...,...,...,...,...,...,...,...,...,...
95,20210811,3ba81ee2-7171-466d-aae2-d5f842a50389,20200728,78,FEMENINO,Criterio serolÃ³gico,PUNO,SAN ROMAN,JULIACA,211101.0
96,20210811,0736b5fb-6b99-4c2c-8c54-dad84d3bfbfe,20200928,30,MASCULINO,Criterio serolÃ³gico,PUNO,SAN ROMAN,JULIACA,211101.0
97,20210811,197854dd-37d1-47ba-89eb-1702dc813418,20210216,66,MASCULINO,Criterio serolÃ³gico,HUANUCO,HUANUCO,MARGOS,100105.0
98,20210811,d1eaedc7-f059-408b-8e29-9a830486010b,20210320,43,MASCULINO,Criterio SINADEF,LIMA,LIMA,LA VICTORIA,150115.0
99,20210811,8830deaf-df38-4623-9c0d-905940cd6d25,20210403,49,MASCULINO,Criterio virolÃ³gico,LIMA,LIMA,LA VICTORIA,150115.0

In [20]:
## Leyendo data de un archivo "excel", todas las hojas existentes
path_ = "./src/input/fallecidos_covid.xlsx"
df_e = pd.read_excel(path_, sheet_name=None)

In [21]:
df_e.keys()

dict_keys(['fallecidos_covid', 'Hoja1'])

In [22]:
df_e['Hoja1']

,FECHA_CORTE,UUID,FECHA_FALLECIMIENTO,EDAD_DECLARADA
0,20210811,8ff6ea53-1467-456b-92ef-4e001ff8a2d6,20210725,65
1,20210811,71be5780-1e0d-4092-9036-af6d408d66e5,20210618,37

In [23]:
# lectura de bd sqlite
import sqlite3
import pandas as pd

path_bd = "./src/input/bitcoin_prices.db"

with sqlite3.connect(path_bd) as conn:
    query = 'SELECT * FROM bitcoin'
    #query = "SELECT * FROM bitcoin where currency='USD' "
    
    df_bitcoin = pd.read_sql_query(query, conn)
    # db_bit = pd.read_sql_table(table_name='bitcoin', con=conn)
    pass
df_bitcoin.head()

  currency       price                 date
0      USD  30587.6751  2023-07-01 20:12:41
1      GBP  25558.8166  2023-07-01 20:12:41
2      EUR  29796.8614  2023-07-01 20:12:41
3      USD  30590.1922  2023-07-01 20:13:23
4      GBP  25560.9198  2023-07-01 20:13:23

In [25]:
df_bitcoin.to_csv('bitcoin2-1.csv', index=True)

In [19]:
df_bitcoin.to_excel('bitcoin.xlsx', index=False)

In [26]:
with sqlite3.connect(path_bd) as conn:   
    # escribo datos en db
    df_bitcoin.to_sql('monedas', conn, index=False, if_exists='append')
    
    # recupero los datos
    query = 'SELECT * FROM monedas'
    df_monedas = pd.read_sql_query(query, conn)
    pass

In [27]:
df_monedas

   currency       price                 date
0       USD  30587.6751  2023-07-01 20:12:41
1       GBP  25558.8166  2023-07-01 20:12:41
2       EUR  29796.8614  2023-07-01 20:12:41
3       USD  30590.1922  2023-07-01 20:13:23
4       GBP  25560.9198  2023-07-01 20:13:23
5       EUR  29799.3133  2023-07-01 20:13:23
6       USD  30522.8049  2023-07-02 09:22:07
7       GBP  25504.6116  2023-07-02 09:22:07
8       EUR  29733.6683  2023-07-02 09:22:07
9       USD  30495.9566  2023-07-02 09:26:55
10      GBP  25482.1774  2023-07-02 09:26:55
11      EUR  29707.5142  2023-07-02 09:26:55
12      USD  30587.6751  2023-07-01 20:12:41
13      GBP  25558.8166  2023-07-01 20:12:41
14      EUR  29796.8614  2023-07-01 20:12:41
15      USD  30590.1922  2023-07-01 20:13:23
16      GBP  25560.9198  2023-07-01 20:13:23
17      EUR  29799.3133  2023-07-01 20:13:23
18      USD  30522.8049  2023-07-02 09:22:07
19      GBP  25504.6116  2023-07-02 09:22:07
20      EUR  29733.6683  2023-07-02 09:22:07
21      USD  30495.9566  2023-07-02 09:26:55
22      GBP  25482.1774  2023-07-02 09:26:55
23      EUR  29707.5142  2023-07-02 09:26:55
24      USD  30587.6751  2023-07-01 20:12:41
25      GBP  25558.8166  2023-07-01 20:12:41
26      EUR  29796.8614  2023-07-01 20:12:41
27      USD  30590.1922  2023-07-01 20:13:23
28      GBP  25560.9198  2023-07-01 20:13:23
29      EUR  29799.3133  2023-07-01 20:13:23
30      USD  30522.8049  2023-07-02 09:22:07
31      GBP  25504.6116  2023-07-02 09:22:07
32      EUR  29733.6683  2023-07-02 09:22:07
33      USD  30495.9566  2023-07-02 09:26:55
34      GBP  25482.1774  2023-07-02 09:26:55
35      EUR  29707.5142  2023-07-02 09:26:55

In [28]:
import pandas as pd

path = './src/input/titanic.csv'

df = pd.read_csv(path, sep=',')
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [29]:
df.to_csv('./scripts/salida_datos/file1.csv', index=False)

In [25]:
df.to_excel('./scripts/salida_datos/file.xlsx', index=False)

In [30]:
with sqlite3.connect('./scripts/pandas.bd') as conn:   
    # escribo datos en db
    df.to_sql('titanic', conn, index=False, if_exists='replace')
    
    # recupero los datos
    query = 'SELECT * FROM titanic'
    df_titanic = pd.read_sql_query(query, conn)
    pass

In [30]:
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [ ]:
# flujo de proceso 
#cargas la data df =pd.read_csv('file')
# df (aplicacs condiciones)

# 2. Exploración de la Data
-----------------------------

La exploración de datos es la etapa donde obtenemos informacion sobre la data cargada, información como: cantidad de registros, visualizar registros de la data, cantidad de columnas, tipos de datos de las columnas, nombre de columnas, etc

In [53]:
# csv(<ruta archivo>, sep=<separador datos>)
df = pd.read_csv('./src/input/primary_results.csv',sep=',')

`shape` nos devuelve el número de filas y columnas

In [32]:
df.shape

(24611, 8)

`head` retorna los primertos 5 resultados contenidos en el dataframe (df)

In [ ]:
# head retorna los primeros 5 resultados del dataframe
df.head(7)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
...,...,...,...,...,...,...,...,...
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000

`tail` retorna los 5 últimos resultados contenidos en el dataframe (df)

In [ ]:
# tail -> retorna los últimos 5 resultados del df
df.tail(2)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.0
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.0
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.0
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.0
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.0

`dtypes` nos indica el tipo de dato para cada una de las columnas del df

In [34]:
df.dtypes

state                     str
state_abbreviation        str
county                    str
fips                  float64
party                     str
candidate                 str
votes                   int64
fraction_votes        float64
dtype: object

`columns` nos indica las columnas que conforman el df

In [37]:
print(df.columns)
type(df.columns)

Index(['state', 'state_abbreviation', 'county', 'fips', 'party', 'candidate',
       'votes', 'fraction_votes'],
      dtype='str')

pandas.Index

`describe` nos brinda un resumen de la cantidad de datos, promedio, desviación estandar, minimo, máximo, etc de los datos de las columnas posibles

In [38]:
# Describe -> nos brinda un resumen de la cantidad de datos, promedio, desviación estandar, minimo, máximo, etc 
# de los datos de las columnas posibles
df.describe()

               fips          votes  fraction_votes
count  2.451100e+04   24611.000000    24611.000000
mean   2.667152e+07    2306.252773        0.304524
std    4.200978e+07    9861.183572        0.231401
min    1.001000e+03       0.000000        0.000000
25%    2.109100e+04      68.000000        0.094000
50%    4.208100e+04     358.000000        0.273000
75%    9.090012e+07    1375.000000        0.479000
max    9.560004e+07  590502.000000        1.000000

# 3. Seleccionando Filas y columnas 
----------------------------

### 3.1 Seleccion de Columnas

In [39]:
df.columns

Index(['state', 'state_abbreviation', 'county', 'fips', 'party', 'candidate',
       'votes', 'fraction_votes'],
      dtype='str')

In [54]:
for c in df.columns:
    print(c,type(c))

state <class 'str'>
state_abbreviation <class 'str'>
county <class 'str'>
fips <class 'str'>
party <class 'str'>
candidate <class 'str'>
votes <class 'str'>
fraction_votes <class 'str'>

Seleccionamos una columna mediante '[]' como si el dataframe fuese un diccionario

In [42]:
# Seleccion de una única columna
df['state'].head()

0    Alabama
1    Alabama
2    Alabama
3    Alabama
4    Alabama
Name: state, dtype: str

In [ ]:
# tambien es posible la seleccion de este modo
#class Person:
#
    #def __init__(self):
        #self.name="gian"
#p1 = Person()
#p1.name
df.state_abbreviation.head()

0    AL
1    AL
2    AL
3    AL
4    AL
Name: state_abbreviation, dtype: str

In [44]:
# Seleccion de más de una columna
columns_select = ['state','state_abbreviation'] # colocamos en una lista las columnas que deseamos
df[columns_select].head()

     state state_abbreviation
0  Alabama                 AL
1  Alabama                 AL
2  Alabama                 AL
3  Alabama                 AL
4  Alabama                 AL

In [45]:
df["state"][:10]

0    Alabama
1    Alabama
2    Alabama
3    Alabama
4    Alabama
5    Alabama
6    Alabama
7    Alabama
8    Alabama
9    Alabama
Name: state, dtype: str

In [46]:
import pandas as pd
import sqlite3

path = './src/input/titanic.csv'

df = pd.read_csv(path, sep=',')
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [47]:
columns = ['PassengerId','Survived','Pclass','Name']

df[columns]
#df['Survived'].unique()

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"
...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas"
887,888,1,1,"Graham, Miss. Margaret Edith"
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell"
890,891,0,3,"Dooley, Mr. Patrick"

### 3.2 Seleccion de Filas

In [48]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [50]:
# valores únicos de columna
df['Name'].unique()

<StringArray>
[                            'Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
                              'Heikkinen, Miss. Laina',
        'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
                            'Allen, Mr. William Henry',
                                    'Moran, Mr. James',
                             'McCarthy, Mr. Timothy J',
                      'Palsson, Master. Gosta Leonard',
   'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
                 'Nasser, Mrs. Nicholas (Adele Achem)',
 ...
                                  'Markun, Mr. Johann',
                        'Dahlberg, Miss. Gerda Ulrika',
                       'Banfield, Mr. Frederick James',
                              'Sutehall, Mr. Henry Jr',
                'Rice, Mrs. William (Margaret Norton)',
                               'Montvila, Rev. Juozas',
                        'Graham, Miss. Margaret Edith',
            'Johnston, Miss. Catherine Helen "Carrie"',
                               'Behr, Mr. Karl Howell',
                                 'Dooley, Mr. Patrick']
Length: 891, dtype: str

In [52]:
# valores únicos de columna
df_var = df[['Survived','Age']].drop_duplicates(subset=['Survived','Age'])

df_var.head()

   Survived   Age
0         0  22.0
1         1  38.0
2         1  26.0
3         1  35.0
4         0  35.0

In [55]:
condicion = (df['state']=='Texas')
df_filter= df[condicion]
df_filter

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
19111,Texas,TX,Anderson,48001.0,Democrat,Bernie Sanders,299,0.227
19112,Texas,TX,Anderson,48001.0,Democrat,Hillary Clinton,994,0.756
19113,Texas,TX,Andrews,48003.0,Democrat,Bernie Sanders,38,0.330
19114,Texas,TX,Andrews,48003.0,Democrat,Hillary Clinton,76,0.661
19115,Texas,TX,Angelina,48005.0,Democrat,Bernie Sanders,622,0.235
...,...,...,...,...,...,...,...,...
20884,Texas,TX,Zavala,48507.0,Republican,Ben Carson,0,0.000
20885,Texas,TX,Zavala,48507.0,Republican,Donald Trump,0,0.000
20886,Texas,TX,Zavala,48507.0,Republican,John Kasich,0,0.000
20887,Texas,TX,Zavala,48507.0,Republican,Marco Rubio,0,0.000
20888,Texas,TX,Zavala,48507.0,Republican,Ted Cruz,0,0.000

In [ ]:
#  Selecciona todas las filas cuyo valor de state sea Texas
condicion = (df['state']=='Texas')
df_filter= df[condicion]

def funcion_filtrar_party(row):
    return (row['party'] == 'Democrat') 
def function_filter_votes(row):
    return row['votes']>=2000
def cleanDni(row):
    return row['dni'] != None
df_filter_v2=df[funcion_filtrar_party]
df_filter_v3=df_filter_v2[function_filter_votes]
df_filter_v3

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
5,Alabama,AL,Barbour,1005.0,Democrat,Hillary Clinton,2567,0.906
11,Alabama,AL,Bullock,1011.0,Democrat,Hillary Clinton,2451,0.913
...,...,...,...,...,...,...,...,...
24294,Wisconsin,WI,Waupaca,55135.0,Democrat,Hillary Clinton,2582,0.397
24297,Wisconsin,WI,Winnebago,55139.0,Democrat,Bernie Sanders,17818,0.612
24298,Wisconsin,WI,Winnebago,55139.0,Democrat,Hillary Clinton,11193,0.385
24299,Wisconsin,WI,Wood,55141.0,Democrat,Bernie Sanders,6747,0.602
24300,Wisconsin,WI,Wood,55141.0,Democrat,Hillary Clinton,4424,0.395

In [57]:
df_filter_v2

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
...,...,...,...,...,...,...,...,...
24558,Wyoming,WY,Uinta,56041.0,Democrat,Hillary Clinton,4,0.444
24559,Wyoming,WY,Washakie,56043.0,Democrat,Bernie Sanders,1,0.333
24560,Wyoming,WY,Washakie,56043.0,Democrat,Hillary Clinton,2,0.667
24561,Wyoming,WY,Weston,56045.0,Democrat,Bernie Sanders,1,0.500
24562,Wyoming,WY,Weston,56045.0,Democrat,Hillary Clinton,1,0.500

In [64]:
columns_select = ['state','party', 'county']
df_var = df_filter[df_filter['votes']>=100]
df_select = df_var[columns_select]
df_select

       state       party    county
19111  Texas    Democrat  Anderson
19112  Texas    Democrat  Anderson
19115  Texas    Democrat  Angelina
19116  Texas    Democrat  Angelina
19117  Texas    Democrat   Aransas
...      ...         ...       ...
20874  Texas  Republican     Young
20875  Texas  Republican     Young
20876  Texas  Republican     Young
20877  Texas  Republican     Young
20878  Texas  Republican     Young

[1246 rows x 3 columns]

La columna a la izquierda del state es el index. Un dataframe tiene que tener un index, que es la manera de organizar los datos.

In [58]:
# nos indica el punto de inicio y fin del indice para el df
df.index

RangeIndex(start=0, stop=24611, step=1)

podemos seleccionar una fila mediante su index.

In [59]:
df.loc[0]

state                        Alabama
state_abbreviation                AL
county                       Autauga
fips                          1001.0
party                       Democrat
candidate             Bernie Sanders
votes                            544
fraction_votes                 0.182
Name: 0, dtype: object

**Importante:** 

df.loc selecciona por indice, no por posición. Podemos cambiar el indice a cualquier otra cosa, otra columna o una lista separada, siempre que el nuevo indice tenga la misma longitud que el Dataframe

In [60]:
df2 = df.set_index("county").copy()

In [64]:
df2.head(3)

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
county,,,,,,,
Autauga,Alabama,AL,1001.0,Democrat,Bernie Sanders,544,0.182
Autauga,Alabama,AL,1001.0,Democrat,Hillary Clinton,2387,0.800
Baldwin,Alabama,AL,1003.0,Democrat,Bernie Sanders,2694,0.329

In [65]:
df2.index

Index(['Autauga', 'Autauga', 'Baldwin', 'Baldwin', 'Barbour', 'Barbour',
       'Bibb', 'Bibb', 'Blount', 'Blount',
       ...
       'Sweetwater-Carbon', 'Sweetwater-Carbon', 'Teton-Sublette',
       'Teton-Sublette', 'Teton-Sublette', 'Teton-Sublette', 'Uinta-Lincoln',
       'Uinta-Lincoln', 'Uinta-Lincoln', 'Uinta-Lincoln'],
      dtype='str', name='county', length=24611)

Esto va a fallar por que df2 no tiene un indice numérico.

In [66]:
df2.loc[0] # loc -> dado que el indice 0 ya no existe

KeyError: 0

Ahora podemos seleccionar por condado

In [67]:
df2.loc["Teton-Sublette"] # seleccionamos filas cuyo indice sea 'Teton-Sublette'

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
county,,,,,,,
Teton-Sublette,Wyoming,WY,95600028.0,Republican,Donald Trump,21,0.525
Teton-Sublette,Wyoming,WY,95600028.0,Republican,John Kasich,0,0.000
Teton-Sublette,Wyoming,WY,95600028.0,Republican,Marco Rubio,19,0.475
Teton-Sublette,Wyoming,WY,95600028.0,Republican,Ted Cruz,0,0.000

Si queremos seleccionar por el numero de fila independientemente del índice, podemos usar `iloc`

In [68]:
df2.iloc[100]

state                        Alabama
state_abbreviation                AL
fips                          1101.0
party                       Democrat
candidate             Bernie Sanders
votes                           4266
fraction_votes                 0.128
Name: Montgomery, dtype: object

In [69]:
df2.iloc[20:25]

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
county,,,,,,,
Chilton,Alabama,AL,1021.0,Democrat,Bernie Sanders,289,0.246
Chilton,Alabama,AL,1021.0,Democrat,Hillary Clinton,860,0.731
Choctaw,Alabama,AL,1023.0,Democrat,Bernie Sanders,273,0.124
Choctaw,Alabama,AL,1023.0,Democrat,Hillary Clinton,1772,0.802
Clarke,Alabama,AL,1025.0,Democrat,Bernie Sanders,213,0.063

In [70]:
# volviendo el indice a su valor inicial
df2.reset_index(drop=True, inplace=True) # inplace -> se encarga de efectuar el cambio sobre el df

In [71]:
df2.head()

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,1005.0,Democrat,Bernie Sanders,222,0.078

# 4. Filtrado de Información
------------------------------

Podemos filtrar un dataframe mediante condiciones booleanas sobre columnas

In [72]:
# condicion -> se encarga de establecer la condicion de Verdad o Falsedad 
condicion = df['votes']>=590502
condicion.head()

0    False
1    False
2    False
3    False
4    False
Name: votes, dtype: bool

In [73]:
# usando la condicion como filtro
df[condicion]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.57

podemos concatenar varias condiciones usando `&` para **AND** ,  `|` para **OR** y `~` como **NOT** o negacion.

Tambien debemos recordar los operadores: `==` , `!=` , `>`, `<` , `>=` , `<=`

In [74]:
condicion  = (df.county=="Manhattan") & (df.party=="Democrat")
df[condicion]

#if 2>3 and 3<5 or 3>2
# &  |  ~    ~

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
15011,New York,NY,Manhattan,36061.0,Democrat,Bernie Sanders,90227,0.337
15012,New York,NY,Manhattan,36061.0,Democrat,Hillary Clinton,177496,0.663

Para ver más formas de filtrado [ver](https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9)

# 5. Procesamiento de Datos
------------------------------

In [75]:
df.head(2)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800

podemos usar `sort_values` para orderar el dataframe acorde al valor de una columna o múltiples columnas

In [78]:
df_sorted = df.sort_values(by=["votes","county"], ascending=[False, True])
df_sorted.head(50)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.570
1385,California,CA,Los Angeles,6037.0,Democrat,Bernie Sanders,434656,0.420
4451,Illinois,IL,Chicago,91700103.0,Democrat,Hillary Clinton,366954,0.536
4450,Illinois,IL,Chicago,91700103.0,Democrat,Bernie Sanders,311225,0.454
4463,Illinois,IL,Cook Suburbs,91700104.0,Democrat,Hillary Clinton,249217,0.536
17309,Pennsylvania,PA,Philadelphia,42101.0,Democrat,Hillary Clinton,212785,0.626
4462,Illinois,IL,Cook Suburbs,91700104.0,Democrat,Bernie Sanders,212428,0.457
1519,California,CA,Los Angeles,6037.0,Republican,Donald Trump,179130,0.698
15012,New York,NY,Manhattan,36061.0,Democrat,Hillary Clinton,177496,0.663
14964,New York,NY,Brooklyn,36047.0,Democrat,Hillary Clinton,174236,0.600
12206,Michigan,MI,Wayne,26163.0,Democrat,Hillary Clinton,163886,0.600
19312,Texas,TX,Harris,48201.0,Democrat,Hillary Clinton,156729,0.705
20123,Texas,TX,Harris,48201.0,Republican,Ted Cruz,147721,0.453
1552,California,CA,Orange,6059.0,Republican,Donald Trump,146888,0.767
800,Arizona,AZ,Maricopa,4013.0,Republican,Donald Trump,144522,0.462
1422,California,CA,San Diego,6073.0,Democrat,Hillary Clinton,139813,0.551
2638,Florida,FL,Broward,12011.0,Democrat,Hillary Clinton,132527,0.725
2712,Florida,FL,Miami-Dade,12086.0,Democrat,Hillary Clinton,129467,0.747
764,Arizona,AZ,Maricopa,4013.0,Democrat,Hillary Clinton,126988,0.581
15996,Ohio,OH,Cuyahoga,39035.0,Democrat,Hillary Clinton,125914,0.632
17308,Pennsylvania,PA,Philadelphia,42101.0,Democrat,Bernie Sanders,125688,0.370
1573,California,CA,San Diego,6073.0,Republican,Donald Trump,124255,0.784
1408,California,CA,Orange,6059.0,Democrat,Hillary Clinton,123723,0.546
17211,Pennsylvania,PA,Allegheny,42003.0,Democrat,Hillary Clinton,122399,0.551
15038,New York,NY,Queens,36081.0,Democrat,Hillary Clinton,122386,0.616
14963,New York,NY,Brooklyn,36047.0,Democrat,Bernie Sanders,116327,0.400
9148,Maryland,MD,Prince George's,24033.0,Democrat,Hillary Clinton,113912,0.742
19224,Texas,TX,Dallas,48113.0,Democrat,Hillary Clinton,113574,0.715
2931,Florida,FL,Miami-Dade,12086.0,Republican,Marco Rubio,111898,0.627
1421,California,CA,San Diego,6073.0,Democrat,Bernie Sanders,111898,0.441
1434,California,CA,Santa Clara,6085.0,Democrat,Hillary Clinton,109963,0.605
9146,Maryland,MD,Montgomery,24031.0,Democrat,Hillary Clinton,109304,0.670
1350,California,CA,Alameda,6001.0,Democrat,Hillary Clinton,107102,0.537
12205,Michigan,MI,Wayne,26163.0,Democrat,Bernie Sanders,104999,0.384
2726,Florida,FL,Palm Beach,12099.0,Democrat,Hillary Clinton,103369,0.715
24181,Wisconsin,WI,Dane,55025.0,Democrat,Bernie Sanders,102585,0.626
16234,Ohio,OH,Franklin,39049.0,Republican,John Kasich,101217,0.637
24238,Wisconsin,WI,Milwaukee,55079.0,Democrat,Hillary Clinton,100932,0.517
1407,California,CA,Orange,6059.0,Democrat,Bernie Sanders,100836,0.445
17210,Pennsylvania,PA,Allegheny,42003.0,Democrat,Bernie Sanders,98012,0.441
14962,New York,NY,Bronx,36005.0,Democrat,Hillary Clinton,95772,0.700
24237,Wisconsin,WI,Milwaukee,55079.0,Democrat,Bernie Sanders,93714,0.480
12168,Michigan,MI,Oakland,26125.0,Democrat,Hillary Clinton,92296,0.514
4700,Illinois,IL,Cook Suburbs,91700104.0,Republican,Donald Trump,91520,0.415
1349,California,CA,Alameda,6001.0,Democrat,Bernie Sanders,91324,0.458
15011,New York,NY,Manhattan,36061.0,Democrat,Bernie Sanders,90227,0.337
13236,Missouri,MO,St. Louis County,29189.0,Democrat,Hillary Clinton,89373,0.553
20718,Texas,TX,Tarrant,48439.0,Republican,Ted Cruz,88867,0.416
17078,Oregon,OR,Multnomah,41051.0,Democrat,Bernie Sanders,87247,0.570
763,Arizona,AZ,Maricopa,4013.0,Democrat,Bernie Sanders,86942,0.398

utilizaremos `groupby` para realizar agrupamientos de informacion sobre una columnas

In [70]:
df.groupby(["state", "party"])

El agrupamiento de datos implica utilizar funciones de agregacion como: `count`, `sum`, `mean`, `min`, `max` a una columna del df

In [79]:
df.groupby(["state", "party"])["votes"].sum()

state          party
Alabama        Democrat       386327
               Republican     837632
Alaska         Democrat          539
               Republican      21930
Arizona        Democrat       399097
                              ...
West Virginia  Republican     188138
Wisconsin      Democrat      1000703
               Republican    1072699
Wyoming        Democrat          280
               Republican        903
Name: votes, Length: 95, dtype: int64

In [74]:
# Agrupo datos y realizo operaciones sobre varias columnas
df.groupby(["state", "party"]).agg({
    'votes': ['min', 'max', 'sum'],
    'fips': 'count'
})

                         votes                   fips
                           min     max      sum count
state         party
Alabama       Democrat      72   67357   386327   134
              Republican     2   32853   837632   335
Alaska        Democrat       0      21      539    80
              Republican     0     464    21930   200
Arizona       Democrat     259  126988   399097    30
...                        ...     ...      ...   ...
West Virginia Republican     5   13936   188138   165
Wisconsin     Democrat     175  102585  1000703   144
              Republican    22   75123  1072699   216
Wyoming       Democrat       0      26      280    46
              Republican     0     141      903    48

[95 rows x 4 columns]

Es posible añadir una nueva columna al df utilizando un valor en especifico

In [86]:
# creo una columna 'nueva_columna' con el valor de 1 
df['nueva_columna'] = 'y'
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y

In [87]:
# puedo realizar operaciones entre columnas

df['votos_2'] = df['votes'] * 2
df['votos_3'] = df['votes'] * df['fraction_votes']

In [88]:
#  + , -, *, /
df

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y
...,...,...,...,...,...,...,...,...,...,...,...
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000,0,0.000,y
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000,0,0.000,y
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000,0,0.000,y
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000,0,0.000,y
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000,106,53.000,y

In [89]:
def get_string_party(partido:str):
    
    if partido == 'Democrat':
        return 'El mejor partido'
    elif partido=='Republican':
        return 'El peor partido'
    else:
        return 'No más pobres en un país rico'

In [85]:
get_string_party('Democrat')

NameError: name 'get_string_party' is not defined

In [90]:
df['slogan_partido'] = df['party'].apply(get_string_party)
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan_partido
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y,El mejor partido
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y,El mejor partido
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y,El mejor partido

In [93]:
df_2 = df.rename(columns={"slogan_partido": "slogan"})

In [82]:
df.rename(columns={"slogan_partido": "Slogan"}, inplace=True)

In [95]:
df.head()
df_2.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y,El mejor partido
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y,El mejor partido
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y,El mejor partido

podemos usar `apply` en una columna para obtener una nueva columna en función de sus valores

In [82]:
# creo una nueva columna a partir de los datos de otra
# df['letra_inicial'] = df.state_abbreviation.apply(lambda s: s[0])  # obtengo primera letra de state_abbreviation

In [98]:
def get_label(fraction:float):
    if fraction>0.2:
        return "Mayor"
    else:
        return "Menor"

In [99]:
df['etiqueta_votos'] = df.fraction_votes.apply(get_label)

In [100]:
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan_partido,etiqueta_votos
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido,Menor
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido,Mayor
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y,El mejor partido,Mayor
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y,El mejor partido,Mayor
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y,El mejor partido,Menor

In [52]:
df.groupby("letra_inicial")["votes"].sum().sort_values()

letra_inicial
H      46886
D     160416
R     179594
U     254203
L     585781
K     760181
S    1225289
V    1984632
G    2032941
A    2686599
W    3010087
P    3176340
F    3940929
O    4904270
T    5348465
C    5590683
I    5657521
N    7329864
M    7884506
Name: votes, dtype: int64

Podemos unir dos dataframes en funcion de sus columnas comunes usando `merge`

La operacion merge implica combinar 2 df a partir de uno o más valores llave o `key`

<img src='./img/merge.png'>

In [101]:
# Descargamos datos de pobreza por condado en US en https://www.ers.usda.gov/data-products/county-level-data-sets/county-level-data-sets-download-data/
df_pobreza = pd.read_csv("./src/input/PovertyEstimates.csv")

In [102]:
df_pobreza.head()

   FIPStxt  PCTPOVALL_2015
0        0            14.7
1     1000            18.5
2     1001            12.7
3     1003            12.9
4     1005            32.0

In [103]:
df.head(2)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan_partido,etiqueta_votos
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido,Menor
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido,Mayor

In [105]:
# Combinando ambas fuentes de datos en un único dataframe a partir de los valores llave
# df_merge = df(df_2, )

df_merge = df.merge(df_pobreza, left_on="fips", right_on="FIPStxt")
df_merge.head()

df_merge.drop(columns=['FIPStxt'], inplace=True)
df_merge.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan_partido,etiqueta_votos,PCTPOVALL_2015
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido,Menor,12.7
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido,Mayor,12.7
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y,El mejor partido,Mayor,12.9
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y,El mejor partido,Mayor,12.9
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y,El mejor partido,Menor,32.0

Como punto general existen diferentes formas de combinar los dataframe, siendo el método `inner` el utilizado por defecto

<img src='./img/merge_tipos.png'>

Como punto final aplicamos un agrupamiento aplicando múltiples funciones de agregacion al df

In [58]:
county_votes = df.groupby(["county","party"]).agg({
    "fraction_votes":"mean",
    "PCTPOVALL_2015": "mean"   
   }
)

In [59]:
county_votes

                      fraction_votes  PCTPOVALL_2015
county    party
Abbeville Democrat          0.494000            19.1
          Republican        0.166667            19.1
Acadia    Democrat          0.425500            23.7
          Republican        0.241750            23.7
Accomack  Democrat          0.497000            20.4
...                              ...             ...
Zapata    Republican        0.188400            30.9
Zavala    Democrat          0.468000            32.0
          Republican        0.000000            32.0
Ziebach   Democrat          0.500000            47.1
          Republican        0.333333            47.1

[3267 rows x 2 columns]

# 6. Exportación de datos
----------------------------------

`Pandas` viene equipado con una amplia gama de opciones para la exportación de información.

podemos escribir a excel, necesitamos instalar el paquete `xlwt`

<img src='https://pandas.pydata.org/docs/_images/02_io_readwrite.svg'>

In [107]:
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan_partido,etiqueta_votos
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido,Menor
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido,Mayor
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y,El mejor partido,Mayor
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y,El mejor partido,Mayor
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y,El mejor partido,Menor

In [112]:
## Expotanción con "encoding" e "index False"

df.to_excel('./src/output/data_partidos.xlsx',sheet_name='data',index=False)

In [94]:
## Exportando a csv
path = './src/output/data_partidos.csv'
df_excel.to_csv(path, sep='|' ,index=False)

In [ ]:
## Exportamos archivo a html

with open('./out/data.html',mode='w') as f:
    f.write(df.to_html())

In [ ]:
df.to_csv('./out/data_partidos.csv',sep='|',encoding='utf-8',index=False)

In [108]:
import sqlite3

with sqlite3.connect('base_datos.db') as conn:
    df_merge.to_sql('partidos', con=conn, index=False, if_exists='replace')

# Ejercicios
---------------------------------------------

1. A partir de la data recien generada "data_partidos.xlsx", debemos generar un archivo que contenda unicamente la información contenida por cada uno de los estados.

In [113]:
## Exportando df a excel
df_excel = pd.read_excel('./src/output/data_partidos.xlsx',sheet_name='data')

In [115]:
df_excel.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,votos_2,votos_3,nueva_columna,slogan_partido,etiqueta_votos
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182,1088,99.008,y,El mejor partido,Menor
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800,4774,1909.600,y,El mejor partido,Mayor
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329,5388,886.326,y,El mejor partido,Mayor
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647,10580,3422.630,y,El mejor partido,Mayor
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078,444,17.316,y,El mejor partido,Menor

In [116]:
estados = df_excel.state.unique()
estados

<StringArray>
[       'Alabama',         'Alaska',        'Arizona',       'Arkansas',
     'California',       'Colorado',    'Connecticut',       'Delaware',
        'Florida',        'Georgia',         'Hawaii',          'Idaho',
       'Illinois',        'Indiana',           'Iowa',         'Kansas',
       'Kentucky',      'Louisiana',          'Maine',       'Maryland',
  'Massachusetts',       'Michigan',    'Mississippi',       'Missouri',
        'Montana',       'Nebraska',         'Nevada',  'New Hampshire',
     'New Jersey',     'New Mexico',       'New York', 'North Carolina',
   'North Dakota',           'Ohio',       'Oklahoma',         'Oregon',
   'Pennsylvania',   'Rhode Island', 'South Carolina',   'South Dakota',
      'Tennessee',          'Texas',           'Utah',        'Vermont',
       'Virginia',     'Washington',  'West Virginia',      'Wisconsin',
        'Wyoming']
Length: 49, dtype: str

In [117]:
import os

In [118]:
# generar un excel para cada uno de los estados, donde la información corresponda a dicho estado.
if not os.path.isdir('./src/output/reportes'):
    os.mkdir('./src/output/reportes')

for estado in estados:
    # filtrar el df
    
    df_filter = df_excel[df_excel['state'] == estado]
    
    # guardar el archivo
    folder = './src/output/reportes/{archivo}.xlsx'
    archivo_name = estado.lower().replace(' ', '')
    
    df_filter.to_excel( folder.format(archivo=archivo_name) ,sheet_name=archivo_name, index=False)
    pass

print('Done!!')

Done!!

In [109]:
# 2. Conectandome a SQL

# server_name
# base_datos
# user, password

In [110]:
!pip install pyodbc --upgrade

Requirement already satisfied: pyodbc in c:\users\gon_2\anaconda3\lib\site-packages (4.0.32)
Collecting pyodbc
  Downloading pyodbc-4.0.34-cp38-cp38-win_amd64.whl (75 kB)
Installing collected packages: pyodbc
  Attempting uninstall: pyodbc
    Found existing installation: pyodbc 4.0.32
    Uninstalling pyodbc-4.0.32:
      Successfully uninstalled pyodbc-4.0.32
Successfully installed pyodbc-4.0.34

In [112]:
import pandas as pd
import pyodbc as podbc


def conexion_sql_server(driver,server,database,username=None,password=None):
    print("realizando conexion SQL")
    # cnxn = pyodbc.connect(r'Driver=SQL Server;Server=.\SQLEXPRESS;Database=myDB;Trusted_Connection=yes;')
    connection = podbc.connect('DRIVER='+driver+     # programa que permite el enlace con el computador 
                                ';SERVER='+server+   # computar o dirección ip de la computadora
                                ';DATABASE='+database+  # colección de tablas
                                ';Trusted_Connection=yes'
                                # ';UID='+username+     # login 
                                # ';PWD='+ password
                              )    #
    print("exito!!")
    return connection

def select_to_df(sql_query,connection):
    #conectando a la base de datos
    try:
        #pasanod info a df
        df = pd.read_sql(sql_query, connection)
    except Exception as e:
        print(e)
    
    #cerrando conexion
    connection.close()
    return df

In [132]:
conn = conexion_sql_server('{SQL Server Native Client 11.0}', 'DESKTOP-04UEK3O', 'AdventureWorks2019')

realizando conexion SQL
exito!!

In [114]:

query = 'select * from AdventureWorks2019.Person.Person'
df_sql = select_to_df(query, conn)

C:\Users\gon_2\anaconda3\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [115]:
df_sql.head()

,BusinessEntityID,PersonType,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,EmailPromotion,AdditionalContactInfo,Demographics,rowguid,ModifiedDate
0,1,EM,False,None,Ken,J,Sánchez,None,0,None,"<IndividualSurvey xmlns=""http://schemas.micros...",92C4279F-1207-48A3-8448-4636514EB7E2,2009-01-07
1,2,EM,False,None,Terri,Lee,Duffy,None,1,None,"<IndividualSurvey xmlns=""http://schemas.micros...",D8763459-8AA8-47CC-AFF7-C9079AF79033,2008-01-24
2,3,EM,False,None,Roberto,None,Tamburello,None,0,None,"<IndividualSurvey xmlns=""http://schemas.micros...",E1A2555E-0828-434B-A33B-6F38136A37DE,2007-11-04
3,4,EM,False,None,Rob,None,Walters,None,0,None,"<IndividualSurvey xmlns=""http://schemas.micros...",F2D7CE06-38B3-4357-805B-F4B6B71C01FF,2007-11-28
4,5,EM,False,Ms.,Gail,A,Erickson,None,0,None,"<IndividualSurvey xmlns=""http://schemas.micros...",F3A3F6B4-AE3B-430C-A754-9F2231BA6FEF,2007-12-30

In [119]:
df_process = df_sql[df_sql.PersonType == 'EM']

In [120]:
df_process.head(2)

,BusinessEntityID,PersonType,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,EmailPromotion,AdditionalContactInfo,Demographics,rowguid,ModifiedDate
0,1,EM,False,None,Ken,J,Sánchez,None,0,None,"<IndividualSurvey xmlns=""http://schemas.micros...",92C4279F-1207-48A3-8448-4636514EB7E2,2009-01-07
1,2,EM,False,None,Terri,Lee,Duffy,None,1,None,"<IndividualSurvey xmlns=""http://schemas.micros...",D8763459-8AA8-47CC-AFF7-C9079AF79033,2008-01-24

In [121]:
df_process.shape

(273, 13)

In [152]:
# escribiendo con pyodbc
conn = conexion_sql_server('{SQL Server Native Client 11.0}', 'DESKTOP-04UEK3O', 'AdventureWorks2019')
cursor=conn.cursor()

# creating column list for insertion
cols = ",".join([str(i) for i in df_process.columns.tolist()])

realizando conexion SQL
exito!!

In [143]:
cols

'BusinessEntityID,PersonType,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,EmailPromotion,AdditionalContactInfo,Demographics,rowguid,ModifiedDate'

In [153]:
x = ",".join(['?' for i in df_process.columns] )
# Insert DataFrame recrds one by one.
for index, row in df_process.iterrows():
     cursor.execute(f"INSERT INTO Person.Person_pandas ({cols}) values({x})",tuple(row))
conn.commit() # confirmación de escritura

In [154]:
cursor.close() # cerrar conección con servidor